### ISSUE TITLE
Failure to Connect to Newly Added Server

### ISSUE THREAD

**Issue by andylenzwx** [Tkd-Alex/dvpn-node-spawner#4]
After setting up the dashboard and adding a new host's credentials, I get an immediate traceback upon attempting to connect my newly added host via the dashboard. Here's the full log output:

```
127.0.0.1 - - [23/Oct/2023 07:50:55] "GET /server/1 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/alenz/dvpn-node-spawner/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/alenz/dvpn-node-spawner/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/alenz/dvpn-node-spawner/venv/lib/python3.11/site-packages/urllib3/connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/http/client.py", line 1378, in getresponse
    response.begin()
  File "/usr/lib/python3.11/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alenz/dvpn-node-spawner/venv/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/alenz/dvpn-node-spawner/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/alenz/dvpn-node-spawner/venv/lib/python3.11/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alenz/dvpn-node-spawner/venv/lib/python3.11/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/alenz/dvpn-node-spawner/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/alenz/dvpn-node-spawner/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/alenz/dvpn-node-spawner/venv/lib/python3.11/site-packages/urllib3/connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/http/client.py", line 1378, in getresponse
    response.begin()
  File "/usr/lib/python3.11/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alenz/dvpn-node-spawner/venv/lib/python3.11/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alenz/dvpn-node-spawner/venv/lib/python3.11/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alenz/dvpn-node-spawner/venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alenz/dvpn-node-spawner/venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alenz/dvpn-node-spawner/venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alenz/dvpn-node-spawner/venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alenz/dvpn-node-spawner/venv/lib/python3.11/site-packages/flask_httpauth.py", line 174, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alenz/dvpn-node-spawner/main.py", line 538, in handle_server
    docker_client = ssh.docker(docker_api_version)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alenz/dvpn-node-spawner/handlers/SSH.py", line 95, in docker
    if client.version(api_version=False)["ApiVersion"] == docker_api_version:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alenz/dvpn-node-spawner/venv/lib/python3.11/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alenz/dvpn-node-spawner/venv/lib/python3.11/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alenz/dvpn-node-spawner/venv/lib/python3.11/site-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alenz/dvpn-node-spawner/venv/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alenz/dvpn-node-spawner/venv/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alenz/dvpn-node-spawner/venv/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alenz/dvpn-node-spawner/venv/lib/python3.11/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
127.0.0.1 - - [23/Oct/2023 07:50:55] "GET /server/1?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 304 -
127.0.0.1 - - [23/Oct/2023 07:50:55] "GET /server/1?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 304 -
127.0.0.1 - - [23/Oct/2023 07:50:55] "GET /server/1?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -
```

**Comment by Tkd-Alex** [comment]
Docker seems to be installed but the script is unable to establish a connection, the docker service is running on your node machine?

**Comment by andylenzwx** [comment]
> Docker seems to be installed but the script is unable to establish a connection, the docker service is running on your node machine?

Okay, I have identified the issue. The SSH user for which I provided the credentials for on the desired node server was not a member of the docker group. The user did have sudo privileges all along, but the node spawner was unable to connect to and configure the node until I added the user to the docker group on the OS as well.

**Comment by Tkd-Alex** [comment]
I'll use it to improve the script, thank you! I'll check also for the docker group ;)

**Comment by andylenzwx** [comment]
> I'll use it to improve the script, thank you! I'll check also for the docker group ;)

Of course! Thank you :)
