### ISSUE TITLE
Remote end closed connection without response

### ISSUE THREAD

**Issue by veris1** [Tkd-Alex/dvpn-node-spawner#6]
![image](https://github.com/Tkd-Alex/dvpn-node-spawner/assets/117972071/5c3a92a9-2446-467f-8566-b4ecfaadbe81)

Traceback (most recent call last):
  File "/home/pi/dvpn-node-spawner/venv/lib/python3.10/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/pi/dvpn-node-spawner/venv/lib/python3.10/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "/home/pi/dvpn-node-spawner/venv/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/dvpn-node-spawner/venv/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/dvpn-node-spawner/venv/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/dvpn-node-spawner/venv/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/pi/dvpn-node-spawner/venv/lib/python3.10/site-packages/flask_httpauth.py", line 174, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/pi/dvpn-node-spawner/main.py", line 538, in handle_server
    docker_client = ssh.docker(docker_api_version)
  File "/home/pi/dvpn-node-spawner/handlers/SSH.py", line 95, in docker
    if client.version(api_version=False)["ApiVersion"] == docker_api_version:
  File "/home/pi/dvpn-node-spawner/venv/lib/python3.10/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/home/pi/dvpn-node-spawner/venv/lib/python3.10/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/home/pi/dvpn-node-spawner/venv/lib/python3.10/site-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/home/pi/dvpn-node-spawner/venv/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/home/pi/dvpn-node-spawner/venv/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/dvpn-node-spawner/venv/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/dvpn-node-spawner/venv/lib/python3.10/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
192.168.31.30 - - [29/Oct/2023 18:58:45] "GET /server/1 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/pi/dvpn-node-spawner/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/home/pi/dvpn-node-spawner/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/home/pi/dvpn-node-spawner/venv/lib/python3.10/site-packages/urllib3/connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/dvpn-node-spawner/venv/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/pi/dvpn-node-spawner/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/home/pi/dvpn-node-spawner/venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/home/pi/dvpn-node-spawner/venv/lib/python3.10/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/pi/dvpn-node-spawner/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/home/pi/dvpn-node-spawner/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/home/pi/dvpn-node-spawner/venv/lib/python3.10/site-packages/urllib3/connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/dvpn-node-spawner/venv/lib/python3.10/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/pi/dvpn-node-spawner/venv/lib/python3.10/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "/home/pi/dvpn-node-spawner/venv/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/dvpn-node-spawner/venv/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/dvpn-node-spawner/venv/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/dvpn-node-spawner/venv/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/pi/dvpn-node-spawner/venv/lib/python3.10/site-packages/flask_httpauth.py", line 174, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/pi/dvpn-node-spawner/main.py", line 538, in handle_server
    docker_client = ssh.docker(docker_api_version)
  File "/home/pi/dvpn-node-spawner/handlers/SSH.py", line 95, in docker
    if client.version(api_version=False)["ApiVersion"] == docker_api_version:
  File "/home/pi/dvpn-node-spawner/venv/lib/python3.10/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/home/pi/dvpn-node-spawner/venv/lib/python3.10/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/home/pi/dvpn-node-spawner/venv/lib/python3.10/site-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/home/pi/dvpn-node-spawner/venv/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/home/pi/dvpn-node-spawner/venv/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/dvpn-node-spawner/venv/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/dvpn-node-spawner/venv/lib/python3.10/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
192.168.31.30 - - [29/Oct/2023 18:58:45] "GET /server/1?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
192.168.31.30 - - [29/Oct/2023 18:58:45] "GET /server/1?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
192.168.31.30 - - [29/Oct/2023 18:58:45] "GET /server/1?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1"

**Comment by Tkd-Alex** [comment]
Probably It's the same as: 
https://github.com/Tkd-Alex/dvpn-node-spawner/issues/4#issuecomment-1781850411

dvpn-node-spawner is unable to use the docker commands so:
- docker service is not active
- the user doesn't have docker permission
